export const FETCH_USERS = 'FETCH_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const CREATE_USER = 'CREATE_USER';

export const APP_LOADING = 'APP_LOADING';
export const APP_LOADING_FINISHED = 'APP_LOADING_FINISHED';
